CREATE TABLE IF NOT EXISTS relationships (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key             UUID NOT NULL UNIQUE,
    actor_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    partner_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status          VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT relationships_actor_partner_unique UNIQUE (actor_id, partner_id),
    CONSTRAINT relationships_actor_partner_check CHECK (actor_id <> partner_id),
    CONSTRAINT relationships_status_check CHECK (status IN ('active', 'pending'))
);

CREATE INDEX IF NOT EXISTS idx_relationships_actor_id ON relationships(actor_id);
CREATE INDEX IF NOT EXISTS idx_relationships_partner_id ON relationships(partner_id);
CREATE INDEX IF NOT EXISTS idx_relationships_status ON relationships(status);

ALTER TABLE mfas
    ADD CONSTRAINT mfas_user_type_unique UNIQUE (user_id, type);
