CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'users'
          AND column_name = 'id'
          AND data_type = 'uuid'
    ) THEN
        ALTER TABLE identities DROP CONSTRAINT IF EXISTS identities_user_id_fkey;
        ALTER TABLE verifications DROP CONSTRAINT IF EXISTS verifications_user_id_fkey;
        ALTER TABLE mfas DROP CONSTRAINT IF EXISTS mfas_user_id_fkey;

        ALTER TABLE identities DROP CONSTRAINT IF EXISTS identities_pkey;
        ALTER TABLE verifications DROP CONSTRAINT IF EXISTS verifications_pkey;
        ALTER TABLE mfas DROP CONSTRAINT IF EXISTS mfas_pkey;
        ALTER TABLE users DROP CONSTRAINT IF EXISTS users_pkey;

        ALTER TABLE identities DROP CONSTRAINT IF EXISTS identities_user_id_provider_key;
        ALTER TABLE verifications DROP CONSTRAINT IF EXISTS verifications_user_id_method_target_key;

        ALTER TABLE users RENAME COLUMN id TO key;
        ALTER TABLE users ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
        ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
        ALTER TABLE users ADD CONSTRAINT users_key_key UNIQUE (key);

        ALTER TABLE identities RENAME COLUMN id TO key;
        ALTER TABLE identities RENAME COLUMN user_id TO user_key;
        ALTER TABLE identities ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
        ALTER TABLE identities ADD COLUMN user_id BIGINT;
        UPDATE identities
        SET user_id = users.id
        FROM users
        WHERE identities.user_key = users.key;
        ALTER TABLE identities ALTER COLUMN user_id SET NOT NULL;
        ALTER TABLE identities DROP COLUMN user_key;
        ALTER TABLE identities ADD CONSTRAINT identities_pkey PRIMARY KEY (id);
        ALTER TABLE identities ADD CONSTRAINT identities_key_key UNIQUE (key);
        ALTER TABLE identities ADD CONSTRAINT identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
        ALTER TABLE identities ADD CONSTRAINT identities_user_id_provider_key UNIQUE (user_id, provider);

        ALTER TABLE verifications RENAME COLUMN id TO key;
        ALTER TABLE verifications RENAME COLUMN user_id TO user_key;
        ALTER TABLE verifications ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
        ALTER TABLE verifications ADD COLUMN user_id BIGINT;
        UPDATE verifications
        SET user_id = users.id
        FROM users
        WHERE verifications.user_key = users.key;
        ALTER TABLE verifications ALTER COLUMN user_id SET NOT NULL;
        ALTER TABLE verifications DROP COLUMN user_key;
        ALTER TABLE verifications ADD CONSTRAINT verifications_pkey PRIMARY KEY (id);
        ALTER TABLE verifications ADD CONSTRAINT verifications_key_key UNIQUE (key);
        ALTER TABLE verifications ADD CONSTRAINT verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
        ALTER TABLE verifications ADD CONSTRAINT verifications_user_id_method_target_key UNIQUE (user_id, method, target);

        ALTER TABLE mfas RENAME COLUMN id TO key;
        ALTER TABLE mfas RENAME COLUMN user_id TO user_key;
        ALTER TABLE mfas ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
        ALTER TABLE mfas ADD COLUMN user_id BIGINT;
        UPDATE mfas
        SET user_id = users.id
        FROM users
        WHERE mfas.user_key = users.key;
        ALTER TABLE mfas ALTER COLUMN user_id SET NOT NULL;
        ALTER TABLE mfas DROP COLUMN user_key;
        ALTER TABLE mfas ADD CONSTRAINT mfas_pkey PRIMARY KEY (id);
        ALTER TABLE mfas ADD CONSTRAINT mfas_key_key UNIQUE (key);
        ALTER TABLE mfas ADD CONSTRAINT mfas_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
        ALTER TABLE mfas ADD CONSTRAINT mfas_user_id_type_key UNIQUE (user_id, type);
    END IF;
END $$;
